### ISSUE TITLE
上传图片后位置展示错误

### ISSUE THREAD

**Issue by Italic-2012** [huashui-ai/public-discussion#1]
## 问题描述
图片上传后，上传占位符未消失；

## 截图或录屏
https://github.com/huashui-ai/public-discussion/assets/24502019/c82c4180-119b-411b-b64a-2cd89a417971

## 我的预期
图片上传成功后，占位符消失

## 复现步骤
- 输入"/"，唤出图片上传占位符
- 点击键盘换行符，新起一行，并输入有效文本
- 最后，点击上传占位符，上传图片

## 相关链接
无

**Comment by wangfupeng1988** [comment]
已经修复，并部署到测试环境 https://preview.huashuiai.com/
