### ISSUE TITLE
对"<无标题>"文档进行复制操作时, 报错"Origin doc not found"

### ISSUE THREAD

**Issue by aotushi** [huashui-ai/public-discussion#19]
请一定按照该模板提交 issue ，谢谢～

## 问题现象

未退出的情况下关闭窗口,通过域名直接访问进入网站.对<无标题>文档进行复制操作,报错提示"Origina doc not found";
页面刷新后,重复操作,正常新增文档"<无标题> 复制".

## 截图或录屏（可选）

https://github.com/huashui-ai/public-discussion/assets/75104303/120199ce-8ab2-40e2-b449-295d7799909c

## 你期望的样子

你预期应该是怎样的？

## 复现步骤

明确的复现步骤，让我可以快速复现问题

- a
- b
- c

## 相关链接

如某个代码文件、wiki 文章等

**Comment by aotushi** [comment]
相同问题
https://github.com/huashui-ai/public-discussion/issues/8

**Comment by wangfupeng1988** [comment]
我没有复线你的问题。你用了什么浏览器？
