### ISSUE TITLE
右上角操作按钮样式显示问题

### ISSUE THREAD

**Issue by arieslx** [huashui-ai/public-discussion#20]
请一定按照该模板提交 issue ，谢谢～

## 问题现象
1. 点击focus已收藏按钮，同时点击“....”按钮，hover效果按钮之间没有边距。

描述问题现象

## 截图或录屏（可选）
<img width="219" alt="image" src="https://github.com/huashui-ai/public-discussion/assets/17746352/549b6e90-8c97-4228-abe3-fc2dfd8fcc3e">

如有需要，请截图或录屏

## 你期望的样子

按钮按照设计定有10px/8px边距，防止按钮hover之后粘粘到一起。

## 复现步骤

明确的复现步骤，让我可以快速复现问题

- a 点击已收藏
- b 点击‘....’按钮
- c 查看两个按钮同时hover的样式

## 相关链接

如某个代码文件、wiki 文章等

**Comment by weiwang-1992** [comment]
代码已开发，
测试步骤：
- 点击文档收藏按钮，将按钮状态变为已收藏
- 测试已收藏按钮和三个点的按钮之间有无margin
@zer0fire 辛苦测试下

**Comment by zer0fire** [comment]
# 测试流程
测试完毕，功能正常
## 功能覆盖表
|功能描述                            | 测试结果  |
| -------------------------|----------|
|收藏和 "..." 键有无 margin | 正确，有 0.2rem 的 margin         |

## 测试截图
![image](https://github.com/huashui-ai/public-discussion/assets/26370252/fd033a30-4487-416e-a57b-441ce8293991)
