### ISSUE TITLE
优化：暗黑模式下，内容显示区色值太深了

### ISSUE THREAD

**Issue by arieslx** [huashui-ai/public-discussion#21]
请一定按照该模板提交 issue ，谢谢～

## 问题现象

优化建议：
调整暗黑模式下黑色色值。

## 截图或录屏（可选）

<img width="1357" alt="image" src="https://github.com/huashui-ai/public-discussion/assets/17746352/a12c6f6e-f149-4476-aad1-b2b815d918cc">

## 你期望的样子

参考舒适一点的暗黑色值，内容显示区域目前的黑色很容易让眼睛疲劳。

## 复现步骤

明确的复现步骤，让我可以快速复现问题

- a 切换dark mode
- b 查看内容显示区

## 相关链接

如某个代码文件、wiki 文章等

**Comment by wangfupeng1988** [comment]
需要给出具体的建议，都用什么颜色值？
