### ISSUE TITLE
复制功能不能复制整个文件夹

### ISSUE THREAD

**Issue by arieslx** [huashui-ai/public-discussion#23]
请一定按照该模板提交 issue ，谢谢～

## 问题现象

1. 在父级文件夹右侧点击扩展按钮，选择复制，只能复制父级文件，不能复制父级及子级文件。

## 截图或录屏（可选）

<img width="434" alt="image" src="https://github.com/huashui-ai/public-discussion/assets/17746352/a894c946-4208-4eed-b932-94c84ee70d3e">

## 你期望的样子

支持复制整个文件夹及内容，要不然就不要把复制按钮放在父级那一层。

## 复现步骤

明确的复现步骤，让我可以快速复现问题

- a 鼠标移动到父级文件夹右侧
- b 点击复制按钮
- c 复制出新的父级文件，但不包含子级文件

## 相关链接

如某个代码文件、wiki 文章等

**Comment by wangfupeng1988** [comment]
这个暂不支持。

第一，如果下面有很多很多子集文件，一次性付出出来，开销会非常大

第二，父级文档也是文档（不是文件夹）也需要复制功能
