### ISSUE TITLE
无限新增新文件，样式显示问题

### ISSUE THREAD

**Issue by arieslx** [huashui-ai/public-discussion#25]
请一定按照该模板提交 issue ，谢谢～

## 问题现象

1. 递归新增文件，嵌套新建文本文件。当新增到几十个文件时标题略缩样式显示有问题。

## 截图或录屏（可选）

<img width="456" alt="image" src="https://github.com/huashui-ai/public-discussion/assets/17746352/774532b2-5b76-4132-b0e7-18185dd55b68">
<img width="549" alt="image" src="https://github.com/huashui-ai/public-discussion/assets/17746352/3dbb4d00-226a-4642-8ea6-a2a2541fc2a1">

## 你期望的样子

Option1:
1. 限制新增文件个数
Option2:
1. 调整显示样式，目前标题样式显示不全。

## 复现步骤

明确的复现步骤，让我可以快速复现问题

- a 新增文件
- b 在新文件下继续新增文件
- c 新增到几十个文件，就能复现

## 相关链接

如某个代码文件、wiki 文章等

**Comment by wangfupeng1988** [comment]
这个不符合实际使用场景。实际场景下最多 3-4 层文件。

这样的样式问题也能阻碍用户增加很多层级，引导他们去做扁平化的文档结构。
