### ISSUE TITLE
优化：收藏夹搜索框固定位置

### ISSUE THREAD

**Issue by djsz3y** [huashui-ai/public-discussion#29]
## 问题现象

收藏夹内容多了以后，收藏夹里的搜索框，没有固定位置，向下滑动内容后，不能随时搜索而不用手动滑动鼠标再搜索

## 截图或录屏（可选）

![image](https://github.com/huashui-ai/public-discussion/assets/59673304/217ee86a-ca51-421b-a5de-da666405dc5d)

![image](https://github.com/huashui-ai/public-discussion/assets/59673304/fe593e0d-1f99-48d5-9642-47a030d98396)

## 你期望的样子

收藏夹内容多了以后，收藏夹里的搜索框，最好固定位置，以便向下滑动内容后，可以随时搜索而不用手动滑动鼠标再搜索

## 复现步骤

- 创建很多个文章，并收藏很多个文章；
- 点击收藏夹；
- 向下滑动最后，找到自己想要的文章；
- 还想找别的，还需要滑动到最上头，找到搜索框搜索。

## 相关链接

无

**Comment by wangfupeng1988** [comment]
回收站也有这个问题，一块改

**Comment by shenjie002** [comment]
**测试分析**: 
1.          当收藏夹列表变多，列表变长，
2.         input 和table的父元素属性**overflow-y-auto**，
3.         用户下滑导致input输入框随滚动条下滑隐藏。
**解决方法**
  1.table整体高度20rem overflow-y:auto 或scroll
<img width="526" alt="1720146682456" src="https://github.com/huashui-ai/public-discussion/assets/88869269/5ac8f153-eec3-455b-a227-c4915587c759">


 2. table 头固定，bodyoverflow-y:auto
 
<img width="501" alt="1720146839468" src="https://github.com/huashui-ai/public-discussion/assets/88869269/1e026cd3-662b-46da-88ec-3a077b132090">

**Comment by wangfupeng1988** [comment]
@shenjie002 我觉得 table head 可以不用固定，固定起来有点难看。

**Comment by shenjie002** [comment]
### 已完成开发
  >>>接下来   --->进入测试阶段
进入系统，将你想收藏/删除的收藏进收藏列表/回收站，
打开收藏夹，查看列表，当收藏文章达到一定高度，滚动滑条，
1.查看滑条滚动;
2.搜索框可正常搜索;
3.完成测试对功能进行测试说明;
4.查看对应代码逻辑给出参考建议;

**Comment by NicCraver** [comment]
# 功能测试报告

| 功能               | 测试结果           | 备注                   |
|--------------------|--------------------|------------------------|
| 收藏夹滑条滚动       | 正确           | 滑条滚动正常          |
| 回收站滑条滚动       | 正确           | 滑条滚动正常          |
| 搜索框可正常搜索   | 正确      | 搜索功能正常          |

**Comment by shenjie002** [comment]
测试详情记录：收藏夹，回收站搜索框不随弹窗右侧滑动条下拉移动，功能已完成，群里找队友测试通过；
                         对于我们功能性相同的标题搜索弹窗，通过队友 @NicCraver @zer0fire  复测中发现，这个全詹性棒；
                         我向双越老师报告，在本次优化中一并解决了。

**Comment by shenjie002** [comment]
本次代码和@shuibuzhuo队友冲突，为代码风格统一，回收站统一采用队友方案处理该优化
