### ISSUE TITLE
主页`github` button 点击无任何响应

### ISSUE THREAD

**Issue by arieslx** [huashui-ai/public-discussion#31]
请一定按照该模板提交 issue ，谢谢～

## 问题现象

主页`github` button 点击无任何响应。

## 截图或录屏（可选）

<img width="1434" alt="image" src="https://github.com/huashui-ai/public-discussion/assets/17746352/c6e088c0-3639-4deb-98cc-0ced20009829">

## 你期望的样子

隐藏或者点击能重定向到对应地址。

## 复现步骤

明确的复现步骤，让我可以快速复现问题

- a
- b
- c

## 相关链接

如某个代码文件、wiki 文章等

**Comment by wangfupeng1988** [comment]
暂时删掉了 github 按钮，反正暂时也没开源
