### ISSUE TITLE
文字链接的'open in new tab'失效

### ISSUE THREAD

**Issue by aotushi** [huashui-ai/public-discussion#35]
请一定按照该模板提交 issue ，谢谢～

## 问题现象

为文档中的两块文字分别添加链接, 链接打开方式中,'Open in new tab'的设置一个打开,一个关闭.
当我点击两个链接时候, 它们都是在新窗口中打开.

## 你期望的样子

你预期应该是怎样的？

## 复现步骤

明确的复现步骤，让我可以快速复现问题

- a
- b
- c

## 相关链接

如某个代码文件、wiki 文章等

**Comment by wangfupeng1988** [comment]
在编辑器内部，肯定都是在新窗口打开。

设置“open in new tab”不是生效在编辑器内部的，就生效在一些预览只读页面（现在还没开发）
