### ISSUE TITLE
主题-深色模式&浅色模式：没有当前选中模式的状态

### ISSUE THREAD

**Issue by djsz3y** [huashui-ai/public-discussion#38]
## 问题现象

主题-深色模式&浅色模式：**没有**当前**选中模式的状态**

## 截图或录屏（可选）

![image](https://github.com/huashui-ai/public-discussion/assets/59673304/9b8d745c-4414-45f5-8026-e881b39d85e9)

## 你期望的样子

当前选中深色模式，或者浅色模式，或者跟随系统，有一个勾选状态。

## 复现步骤

明确的复现步骤，让我可以快速复现问题

- 点击主题
- 选择主题对应的模式：Light、Dark、System。

## 相关链接

**Comment by wangfupeng1988** [comment]
该问题暂缓修改
