### ISSUE TITLE
收藏夹&回收站：一打开，叉号关闭按钮显示了focus聚焦状态，显示应去掉focus聚焦状态。

### ISSUE THREAD

**Issue by djsz3y** [huashui-ai/public-discussion#39]
## 问题现象

收藏夹&回收站：一打开，叉号关闭按钮显示了focus聚焦状态，显示应去掉focus聚焦状态。

## 截图或录屏（可选）

![image](https://github.com/huashui-ai/public-discussion/assets/59673304/9fad0458-2426-4828-93e7-577eca6ec51e)

## 你期望的样子

- 点击收藏夹/回收站
- 看到叉号没有focus聚焦状态

## 复现步骤

- 点击收藏夹/回收站
- 看到叉号有聚焦 focus 的状态

## 相关链接

**Comment by Mengyao-Li** [comment]
经测试发现，回收站和收藏夹一打开聚焦于右上角的×是因为没有其他可聚焦的元素
解决方法1：在Dialog里面插入一个可聚焦的元素但不显示比如<button/>页面加载的时候设置聚焦到button组件上
解决方法2：在Trash组件中改变下显示方式，将搜索框一开始就显示，根据状态显示loading,暂无数据以及表格。这样一打开，默认会聚焦到输入框
解决方法3：在1的基础上，先使用方法1，有结果的时候再聚焦到搜索框

**Comment by Mengyao-Li** [comment]
开发已完成,现进入测试阶段
测试过程:打开回收站和收藏夹,看有上角的关闭按钮是否处于focus状态,正常应为关闭按钮不处于foucs状态,foucs到输入框

**Comment by shenjie002** [comment]
>
| 功能描述 | 测试结果 | 备注 |
|--------|--------|--------|
| 收藏夹Modal框右上角关闭按钮是否是聚焦状态| 打开不聚焦，正确 |  |
| 回收站 | 打开不聚焦，正确 | |
| 收藏夹和回收站 | 打开聚焦到搜索框中，正确 | |
