### ISSUE TITLE
删除的文章恢复失败

### ISSUE THREAD

**Issue by Italic-2012** [huashui-ai/public-discussion#4]
## 问题现象

文章删除后，在回收站内恢复失败

## 截图或录屏（可选）

https://github.com/huashui-ai/public-discussion/assets/24502019/dc071944-06b2-438f-a19c-880b3b54a2e5

## 我的预期
恢复末级层级时，其所有父级层级跟随恢复。或回收站内展示层级结构，仅支持顶级层级恢复(mac回收站逻辑)

## 复现步骤

- 新建层级2，层级2下新建层级3和层级4
- 依次删除层级3、4、2
- 回收站内恢复3、4

## 相关链接

无

**Comment by wangfupeng1988** [comment]
已经修复，并部署到测试环境 https://preview.huashuiai.com/

**Comment by Italic-2012** [comment]
> 已经修复，并部署到测试环境 https://preview.huashuiai.com/

优先恢复子级，恢复的子级会作为顶级展示出来，并不会同时恢复父级，现在是用这个逻辑吗？

**Comment by wangfupeng1988** [comment]
> 优先恢复子级，恢复的子级会作为顶级展示出来，并不会同时恢复父级，现在是用这个逻辑吗？

是的
