### ISSUE TITLE
AI富文本编辑-有序列表**无法**直接设置为标题3。

### ISSUE THREAD

**Issue by djsz3y** [huashui-ai/public-discussion#40]
## 问题现象

AI富文本编辑-有序列表**无法**直接设置为标题3。

## 截图或录屏（可选）

![image](https://github.com/huashui-ai/public-discussion/assets/59673304/34db21fd-aa2e-4e12-95d4-c86b52ff783c)

## 你期望的样子

文本编辑器中的 有序列表，**期望**可以直接设置为标题3/标题2/标题1。

## 复现步骤

- 选中一个有序列表
- 在弹出的菜单框中，第二个菜单选项下拉中，无法选择标题3

![image](https://github.com/huashui-ai/public-discussion/assets/59673304/fbd75be1-0c3b-4961-9e5d-a39bfb2ae6dc)

## 相关链接

无

**Comment by wangfupeng1988** [comment]
这个暂不支持。
