### ISSUE TITLE
AI富文本编辑器-有序列表无法直接设置为标题3

### ISSUE THREAD

**Issue by djsz3y** [huashui-ai/public-discussion#41]
## 问题现象

AI富文本编辑器-有序列表无法直接设置为标题3

## 你期望的样子

- 选中有序列表，弹出菜单
- 点击菜单第2个，**期望可以**设置为标题3/标题2/标题1

## 复现步骤

- 选中有序列表，弹出菜单
- 点击菜单第2个，无法设置为标题3

## 相关链接

**Comment by wangfupeng1988** [comment]
暂不支持该功能
